version: '3.1'

services:
  apiservice:
    container_name: 'backend_apiservice'
    image: apiservice
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 4000:3000
    depends_on:
      - db
  db:
    container_name: 'mysql_database'
    image: mysql:latest
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123  # the root password
      MYSQL_DATABASE: expedia # the default database when connect
      MYSQL_USER : booktip   # create a new user for MYSQL_DATABASE has been specificed
      MYSQL_PASSWORD: booktip # the new user's password
      MYSQL_ALLOW_EMPTY_PASSWORD: 'false'  # allow the root to be connect by empty password
    ports:
      - 3306:3306
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080